# Generated by Django 4.2 on 2023-05-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwapSmart', '0002_category_remove_transaction_listing_ad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='listing',
            new_name='ad',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='categories/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
